### ISSUE TITLE
add lucee issues to cfbugs

### ISSUE THREAD

**Issue by ryanguill** [atuttle/zoidbox#16]

**Comment by ryanguill** [comment]
https://github.com/atuttle/zoidbox/commit/0feb96cd03c3ecf6fea78bce35e791137cc37cbf

**Comment by atuttle** [comment]
FYI you can use a commit message like "resolves #16" and GitHub will
recognize that and close the bug as well as leaving a link here in the
issue history to the commit. Also "relates to #16" or I think even just
"#16" will leave the link here in the issue history without closing the
issue.

All of these support additional content in the message, too. "Resolve #16.
Added lucee to cfbugs"

**Comment by ryanguill** [comment]
Yeah, I know, I  just didnt think about it when making the commit message.  But I wanted to make sure the commit was linked to the issue for history.
