### ISSUE TITLE
!log or !tail

### ISSUE THREAD

**Issue by ryanguill** [atuttle/zoidbox#23]
```
fusiongrokker> It'll take some research but I wonder if we could do a !logs that could dump the last ~20 messages into a gist and then link it or something
<RyanGuill> hmm
<RyanGuill> should be easy, the only part that might be hard is holding on to that rolling buffer in memory (hard being memory usage constraints, not sure what those are)
<fusiongrokker> is there a rolling buffer thing in redis?
<RyanGuill> itd be nice to be able to do !tail 100
<RyanGuill> goo dquestion
<RyanGuill> looks like we could do it with lists - LPUSH RPOP LRANGE
<fusiongrokker> I've got a fire this morning
<RyanGuill> ill put an issue out there
```

**Comment by atuttle** [comment]
I also think holding it in app memory will be of limited utility. Offloading it to redis/etc will make it more useful in debugging a crash.

**Comment by ryanguill** [comment]
agreed.  it will take a bit more to run it through redis but shouldn't be bad.

**Comment by ryanguill** [comment]
probably need to make it a configuration option on how much rolling history to keep (max log).

Will also need to keep in mind to log the output of zoidbox, not just incoming messages (currently we dont listen to output for message counts for instance)

**Comment by atuttle** [comment]
We can add any commands we want to the build & deploy process, e.g. `npm transpile` which would refer to `{"scripts": { "transpile": "whatever we want here" } }` from package.json, or we could make it part of the zoidbox startup itself, sort of how TaffyDocs [compiles markdown into HTML](https://github.com/atuttle/TaffyDocs/blob/master/index.js#L38) during its startup.

**Comment by ryanguill** [comment]
remove ```#maxHistoryPerChannel``` and add to the output of ```#taillen```
Currently doesn't log /me references, need to investigate

**Comment by ryanguill** [comment]
also do not log channels that dont start with a ```#``` so that we don't log PM conversations.
