### ISSUE TITLE
Parse bitbucket and github issues and show relevant data

### ISSUE THREAD

**Issue by ryanguill** [atuttle/zoidbox#26]
If someone links to a bitbucket or github issue, show the status, title and link to the issue
possibly labels for github and type for bitbucket

https://developer.github.com/v3/issues/#list-issues-for-a-repository

example https://api.github.com/repos/atuttle/zoidbox/issues/26

**Comment by atuttle** [comment]
Wouldn't link be redundant if this is initiated by seeing a link?

**Comment by ryanguill** [comment]
yeah - was hoping to keep the same function for everything, but youre probably right.  we can do it differently for this.
