### ISSUE TITLE
Create a plugin to do temperature conversions

### ISSUE THREAD

**Issue by dskaggs** [atuttle/zoidbox#29]
We talk about temperatures enough with people from both sides of the pond that it would be nice to have a simple temperature conversion command.

Either have an on-demand conversion like:
!temp 25f
zoidbox: 25 degrees fahrenheit is -3.9 degrees celcius

Or have it look at every message for a pattern of something like 25c and auto convert it to fahrenheit and vice versa.

**Comment by atuttle** [comment]
:+1:

**Comment by ryanguill** [comment]
need to support negative temperatures and need to change the regex to require whitespace in front of the temp
```
<Kalculus> In CF10, when I try accessing an application variable (in a named application scope) through an included JSP, it doesn't seem to work.  In http://help.adobe.com/en_US/ColdFusion/10.0/Developing/WSc3ff6d0ea77859461172e0811cbec22c24-786c.html it gives sample code on how to do it, but it doesn't seem to work.  Does anyone know how to get this to work.
<zoidbox> BTW, 786ºC is ~1447ºF
```

**Comment by atuttle** [comment]
Ha, it's actually currently using word boundaries, but I can see how whitespace would be better! Will jump on this after lunch.

**Comment by atuttle** [comment]
544dcc109 and f210e4a29
